name: Build and Test
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: git config email
        run: git config --local user.email tiktokbot@users.noreply.github.com
      - name: git config name
        run: git config --local user.name tiktokbot
      - name: Verify Change Logs
        run: node common/scripts/install-run-rush.js change --verify
      - name: Rush Install
        run: node common/scripts/install-run-rush.js install
      - name: Rush rebuild
        run: node common/scripts/install-run-rush.js rebuild --verbose --production
      - name: Rush test
        run: node common/scripts/install-run-rush.js test --verbose
